use_frameworks!

platform :ios, '8.0'

target 'NativeIntegration_Example' do
  pod 'NativeIntegration', :path => '../'

  target 'NativeIntegration_Tests' do
    inherit! :search_paths

    
  end
end
